ALTER TABLE T_MALL_ORDERS_PRIZE
ADD COLUMN SELLER_FEES double DEFAULT 0 COMMENT '卖家运费' AFTER FEES;

INSERT INTO `T_SYSPARA` (`UUID`, `CODE`, `PARTY_ID`, `SVALUE`, `SORDER`, `STYPE`, `NOTES`, `MODIFY`, `BAG_TYPE`) VALUES ('order-freight', 'order-freight', NULL, '1', 100, 2, '订单运费设置', 0, 0);

